apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 2
  selector:
    matchLabels:
        app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: backend
        image: asia-southeast2-docker.pkg.dev/GCP_PROJECT/AR_REPO_NAME/go-api:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1000Mi
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: go-api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-api
spec:
  ingressClassName: nginx
  rules:
    - host: go-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:  
              service:
                name: go-api
                port:
                  number: 8080